#!/usr/bin/env ruby

require "feedproxy"
require "sinatra"

get "/feed" do
  halt 404 if params["url"].nil?
  content_type :json

  feed = Feedproxy::Feed.new(params["url"])

  feed.items.to_json
end
